name: main
on:
  push:
    branches:
      - main
jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
